name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install packages
              run: pip install -r requirements.txt

            - name: Run tests
              run: python manage.py test

            # # Set the environment variables for BAD_HASH and GOOD_HASH
            # - name: Set up Git Bisect Variables
            #   id: bisect_vars
            #   run: |
            #       # Trouver le dernier commit ayant passé les tests
            #       GOOD_HASH=$(git log --grep='Tests passed' -1 --pretty=format:"%H")
            #       echo "GOOD_HASH=$GOOD_HASH" >> $GITHUB_ENV

            #       # Utiliser le commit actuel comme BAD_HASH
            #       BAD_HASH=$(git rev-parse HEAD)
            #       echo "BAD_HASH=$BAD_HASH" >> $GITHUB_ENV

            # # Debug: Print BAD_HASH and GOOD_HASH to ensure they are set
            # - name: Debug Print
            #   run: |
            #       echo "BAD_HASH=$BAD_HASH"
            #       echo "GOOD_HASH=$GOOD_HASH"

            # Execute the bisect action if tests fail
            - name: Execute the bisect action
              if: failure()
              run: python myscript.py
